In [1]:
import numpy as np

def calculate_accompany_t(alpha,beta):
    """
    alpha: 绕X轴的角度，注意正负
    beta: 绕Y轴的角度，注意正负
    """
    angle_x = np.radians(alpha)
    angle_y = np.radians(beta)
    t = np.array([np.sin(angle_y) * 0.1014, -((0.1014*np.cos(angle_y)+0.015)*np.sin(angle_x)), -(0.11640-((0.1014*np.cos(angle_y)+0.015)*np.cos(angle_x)))])
    return t

In [6]:
T_accompany= calculate_accompany_t(34.37,43.10)

T = np.asarray([2, 1, -2]) + T_accompany
T 

array([ 2.06928396,  0.94973469, -2.04290684])

In [15]:
x = np.sin(angle) * 101.4
angle2 = np.radians(34.37)

In [20]:
-(116.40-((101.4*np.cos(angle)+15)*np.cos(angle2)))

-42.906840107499306

In [19]:
-((101.4*np.cos(angle)+15)*np.sin(angle2))

-50.265314989305004

In [21]:
def calculate_accompany_t(alpha,beta):
    engle_x = np.radians(alpha)
    engle_y = np.radians(beta)
    t = np.array([np.sin(angle) * 101.4, -((101.4*np.cos(angle)+15)*np.sin(angle2)), -(116.40-((101.4*np.cos(angle)+15)*np.cos(angle2)))])
    return t


In [22]:
T = calculate_accompany_t(43.10, 34.37)
T

array([ 69.28396065, -50.26531499, -42.90684011])

In [2]:
# 通过列表创建矩阵
matrix_e = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
matrix_u = np.array([[1/2**0.5, 1/(2**0.5), 0], [-1/(2**0.5), 1/(2**0.5), 0], [0, 0, 1]])



In [3]:
print(matrix_e)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [4]:
print(matrix_u)

[[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [5]:
a = np.array([2,4,5])
a

array([2, 4, 5])

In [6]:
transposed_matrix_u = np.transpose(matrix_u)  #旋转矩阵，转置之后左乘
print(transposed_matrix_u)

[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [7]:
result_multiplication = np.dot(transposed_matrix_u, matrix_e)
print(result_multiplication)

[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [8]:
output_a = np.dot(result_multiplication, a)
print(output_a)

[-1.41421356  4.24264069  5.        ]


In [9]:
t = np.array([1, 2, 3])
t
t[ :, np.newaxis]

array([[1],
       [2],
       [3]])

In [10]:
output_b = output_a + t
print(output_b)

[-0.41421356  6.24264069  8.        ]


In [11]:
import numpy as np

# 创建一个二维矩阵
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# 在行上添加新的维度，即将二维矩阵变为三维矩阵
expanded_matrix = matrix[:, :, np.newaxis]
print(expanded_matrix)
np.hstack(( t, np.array([1])))

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


array([1, 2, 3, 1])

In [18]:
# 使用了齐次坐标下面的欧氏变换

np.vstack((result_multiplication, [0, 0, 0]))
np.hstack(( t, np.array([1])))
mm = np.hstack((np.vstack((result_multiplication, [0, 0, 0])), np.hstack(( t, np.array([1])))[:, np.newaxis]))
mm

array([[ 0.70710678, -0.70710678,  0.        ,  1.        ],
       [ 0.70710678,  0.70710678,  0.        ,  2.        ],
       [ 0.        ,  0.        ,  1.        ,  3.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [17]:
import pandas as pd

# 假设 matrix 是你要保存的矩阵


# 创建 DataFrame 对象
df = pd.DataFrame(mm)

# 保存 DataFrame 到 CSV 文件
df.to_csv('matrix.csv', index=False, header=False)


In [13]:
np.dot(mm,np.array([2,4,5,1]))

array([-0.41421356,  6.24264069,  8.        ,  1.        ])

In [14]:
## 欧拉角就是一种将复杂三维旋转变换分解为分别绕三个独立轴转动角度的复合变换的描述，它使用了3个分离的转角，把一个旋转分解成3次绕不同轴的旋转。
## 需要明确旋转顺序，才能确定最终欧拉角所指的姿态

In [15]:
import numpy as np
def euler_to_rotation_matrix(yaw, pitch, roll):
    # Convert degrees to radians
    yaw_rad = np.radians(yaw)
    pitch_rad = np.radians(pitch)
    roll_rad = np.radians(roll)

    # Calculate rotation matrix
    R_x = np.array([[1, 0, 0],
                    [0, np.cos(roll_rad), -np.sin(roll_rad)],
                    [0, np.sin(roll_rad), np.cos(roll_rad)]])

    R_y = np.array([[np.cos(pitch_rad), 0, np.sin(pitch_rad)],
                    [0, 1, 0],
                    [-np.sin(pitch_rad), 0, np.cos(pitch_rad)]])

    R_z = np.array([[np.cos(yaw_rad), -np.sin(yaw_rad), 0],
                    [np.sin(yaw_rad), np.cos(yaw_rad), 0],
                    [0, 0, 1]])

    # Combine the rotations in ZYX order
    #R = np.dot(R_z, np.dot(R_y, R_x))
    #R = np.dot(R_y, np.dot(R_z, R_x))
    R = np.dot(R_x, np.dot(R_y, R_z))
    #R = np.dot(R_z, np.dot(R_y, R_x))
    return R
# 示例用法
yaw_angle =0   # 偏航角Z
pitch_angle = -15 # 俯仰角Y
roll_angle = -15  # 滚转角X

rotation_matrix = euler_to_rotation_matrix(yaw_angle, pitch_angle, roll_angle)

print(rotation_matrix)

[[ 0.96592583  0.         -0.25881905]
 [ 0.0669873   0.96592583  0.25      ]
 [ 0.25       -0.25881905  0.9330127 ]]
